# Generated by Django 5.0.1 on 2026-03-21 06:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', help_text='Restaurant description and about information')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number')])),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('address', models.CharField(blank=True, help_text='Restaurant physical address', max_length=255)),
                ('opening_hours', models.CharField(blank=True, help_text='Opening hours (e.g., 10:00 AM - 10:00 PM)', max_length=100)),
                ('latitude', models.FloatField(blank=True, help_text='Latitude for map', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude for map', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer name', max_length=100)),
                ('email', models.EmailField(help_text='Customer email address', max_length=254)),
                ('phone_number', models.CharField(help_text='Customer contact number', max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number')])),
                ('total_persons', models.IntegerField(help_text='Number of people (1-20)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('booking_date', models.DateField(help_text='Date of booking')),
                ('booking_time', models.TimeField(default='19:00', help_text='Preferred booking time')),
                ('special_requests', models.TextField(blank=True, help_text='Any special requirements (e.g., high chair, allergy info)')),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending', help_text='Current booking status', max_length=20)),
                ('confirmation_sent', models.BooleanField(default=False, help_text='Has confirmation email been sent?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Table Bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking_date', 'status'], name='Base_App_bo_booking_3c7cab_idx'), models.Index(fields=['status', '-created_at'], name='Base_App_bo_status_6c8666_idx')],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Anonymous', help_text='Name of the reviewer', max_length=100)),
                ('email', models.EmailField(help_text='Email of the reviewer', max_length=254)),
                ('description', models.TextField(help_text='Detailed review/feedback')),
                ('rating', models.IntegerField(choices=[(1, '⭐ Poor'), (2, '⭐⭐ Fair'), (3, '⭐⭐⭐ Good'), (4, '⭐⭐⭐⭐ Very Good'), (5, '⭐⭐⭐⭐⭐ Excellent')], help_text='Rating from 1-5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('image', models.ImageField(blank=True, help_text='Optional image from reviewer', null=True, upload_to='feedback/')),
                ('is_approved', models.BooleanField(default=False, help_text='Has this review been approved?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_approved', '-created_at'], name='Base_App_fe_is_appr_ada89c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='Uncategorized', help_text='Category name (e.g., Appetizers, Main Course, Desserts)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('display_order', models.IntegerField(default=0, help_text='Order to display categories')),
                ('is_active', models.BooleanField(default=True, help_text='Hide/show this category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Item Lists',
                'ordering': ['display_order', 'category_name'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='Base_App_it_is_acti_232f69_idx')],
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='Unknown Item', help_text='Name of the menu item', max_length=100)),
                ('description', models.TextField(default='', help_text='Detailed description of the item')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the item', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(default='items/default.png', help_text='Item image', upload_to='items/')),
                ('is_available', models.BooleanField(default=True, help_text='Is this item available for ordering?')),
                ('is_vegetarian', models.BooleanField(default=False, help_text='Is this item vegetarian?')),
                ('is_vegan', models.BooleanField(default=False, help_text='Is this item vegan?')),
                ('is_spicy', models.BooleanField(default=False, help_text='Is this item spicy?')),
                ('preparation_time', models.IntegerField(default=15, help_text='Estimated preparation time in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Base_App.itemlist')),
            ],
            options={
                'verbose_name_plural': 'Items',
                'ordering': ['category', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(help_text='IP address of user (for anonymous users)', max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(help_text='Favorite item', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='Base_App.items')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Offer title', max_length=100)),
                ('description', models.TextField(help_text='Detailed offer description')),
                ('discount_percentage', models.IntegerField(help_text='Discount percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('valid_from', models.DateTimeField(help_text='Offer start date and time')),
                ('valid_until', models.DateTimeField(help_text='Offer end date and time')),
                ('image', models.ImageField(blank=True, help_text='Offer banner image', upload_to='offers/')),
                ('is_active', models.BooleanField(default=True, help_text='Is this offer currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_items', models.ManyToManyField(blank=True, help_text='Items this offer applies to (leave empty for all)', to='Base_App.items')),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='BookingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('confirmation', 'Booking Confirmation'), ('reminder_24h', '24 Hour Reminder'), ('reminder_2h', '2 Hour Reminder'), ('cancellation', 'Cancellation'), ('completion', 'Booking Completed')], help_text='Type of notification', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=True, help_text='Was notification sent successfully?')),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed')),
                ('booking', models.ForeignKey(help_text='Related booking', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Base_App.booktable')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['booking', 'notification_type'], name='Base_App_bo_booking_04391a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='items',
            index=models.Index(fields=['category', 'is_available'], name='Base_App_it_categor_59d01e_idx'),
        ),
        migrations.AddIndex(
            model_name='items',
            index=models.Index(fields=['is_available'], name='Base_App_it_is_avai_6c12b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteitem',
            unique_together={('user_ip', 'item')},
        ),
        migrations.AddIndex(
            model_name='specialoffer',
            index=models.Index(fields=['is_active', '-valid_from'], name='Base_App_sp_is_acti_2cf0d5_idx'),
        ),
    ]
