# Generated by Django 5.0.1 on 2026-03-22 04:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Customer full name', max_length=100)),
                ('customer_email', models.EmailField(help_text='Customer email address', max_length=254)),
                ('customer_phone', models.CharField(help_text='Customer phone number', max_length=15)),
                ('delivery_type', models.CharField(choices=[('delivery', 'Home Delivery'), ('pickup', 'Pickup')], default='delivery', help_text='Delivery or Pickup', max_length=20)),
                ('delivery_address', models.TextField(help_text='Full delivery address')),
                ('delivery_city', models.CharField(default='Bangalore', help_text='City for delivery', max_length=50)),
                ('delivery_pincode', models.CharField(help_text='Pincode/Postal code', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total order amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('special_requests', models.TextField(blank=True, help_text='Special instructions (allergies, preferences, etc.)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', help_text='Order status', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Payment status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, help_text='Estimated delivery time', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='Base_App_or_status_35a6d5_idx'), models.Index(fields=['customer_email', '-created_at'], name='Base_App_or_custome_6f1d18_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Quantity ordered', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_at_purchase', models.DecimalField(decimal_places=2, help_text='Item price at time of order', max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal for this item', max_digits=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(help_text='Menu item ordered', on_delete=django.db.models.deletion.CASCADE, to='Base_App.items')),
                ('order', models.ForeignKey(help_text='Order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Base_App.order')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
