# Generated by Django 5.0.1 on 2026-09-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0004_coupon_items_stock_quantity_items_track_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
